//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatswordsTab.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatswordsTab.Shell.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   가입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabAuth_btnApply {
            get {
                return ResourceManager.GetString("CatswordsTabAuth_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabAuth_btnForgot {
            get {
                return ResourceManager.GetString("CatswordsTabAuth_btnForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabAuth_btnLogin {
            get {
                return ResourceManager.GetString("CatswordsTabAuth_btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (c) Catswords Community. exts.kr과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabAuth_labelCopyright {
            get {
                return ResourceManager.GetString("CatswordsTabAuth_labelCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글쓰기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabPage_btnAdd {
            get {
                return ResourceManager.GetString("CatswordsTabPage_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabPage_btnAuth {
            get {
                return ResourceManager.GetString("CatswordsTabPage_btnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabPage_btnAuth_logout {
            get {
                return ResourceManager.GetString("CatswordsTabPage_btnAuth_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   커뮤니티과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabPage_labelTitle {
            get {
                return ResourceManager.GetString("CatswordsTabPage_labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   커뮤니티과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CatswordsTabPage_PageTitle {
            get {
                return ResourceManager.GetString("CatswordsTabPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon icon_icons_retro_flower_fire_2_24692 {
            get {
                object obj = ResourceManager.GetObject("icon_icons_retro_flower_fire_2_24692", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icondb_white_edit_32 {
            get {
                object obj = ResourceManager.GetObject("icondb_white_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_General_Office_48_3592847 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_General_Office_48_3592847", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_pencil_01_374624 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_pencil_01_374624", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_shining_mix_wrench_1059388 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_shining_mix_wrench_1059388", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_simpline_24_2305594 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_simpline_24_2305594", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_simpline_45_2305617 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_simpline_45_2305617", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconsdb_white_account_login_32 {
            get {
                object obj = ResourceManager.GetObject("iconsdb_white_account_login_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconsdb_white_check_mark_3_32 {
            get {
                object obj = ResourceManager.GetObject("iconsdb_white_check_mark_3_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] NotoSansCJKkr_Regular {
            get {
                object obj = ResourceManager.GetObject("NotoSansCJKkr_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
