//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatswordsTab.App.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatswordsTab.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap become_a_patron_button {
            get {
                object obj = ResourceManager.GetObject("become_a_patron_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap become_a_patron_button_2x {
            get {
                object obj = ResourceManager.GetObject("become_a_patron_button_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnWriter_en {
            get {
                return ResourceManager.GetString("btnWriter_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의견작성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnWriter_ko {
            get {
                return ResourceManager.GetString("btnWriter_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_icons_retro_flower_fire_2_24692_16 {
            get {
                object obj = ResourceManager.GetObject("icon_icons_retro_flower_fire_2_24692_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icondb_white_edit_32 {
            get {
                object obj = ResourceManager.GetObject("icondb_white_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_General_Office_48_3592847 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_General_Office_48_3592847", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_pencil_01_374624 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_pencil_01_374624", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_shining_mix_wrench_1059388 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_shining_mix_wrench_1059388", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_simpline_24_2305594 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_simpline_24_2305594", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_simpline_45_2305617 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_simpline_45_2305617", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconsdb_white_account_login_32 {
            get {
                object obj = ResourceManager.GetObject("iconsdb_white_account_login_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconsdb_white_check_mark_3_32 {
            get {
                object obj = ResourceManager.GetObject("iconsdb_white_check_mark_3_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Community과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelTitle_en {
            get {
                return ResourceManager.GetString("labelTitle_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   커뮤니티과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelTitle_ko {
            get {
                return ResourceManager.GetString("labelTitle_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File could not recognized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msgNotRecognized_en {
            get {
                return ResourceManager.GetString("msgNotRecognized_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일을 인식할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msgNotRecognized_ko {
            get {
                return ResourceManager.GetString("msgNotRecognized_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Community과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageTitle_en {
            get {
                return ResourceManager.GetString("PageTitle_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   커뮤니티과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageTitle_ko {
            get {
                return ResourceManager.GetString("PageTitle_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon Ph03nyx_Super_Mario_Retro_Flower_Fire_2 {
            get {
                object obj = ResourceManager.GetObject("Ph03nyx_Super_Mario_Retro_Flower_Fire_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string txtTerminal_en {
            get {
                return ResourceManager.GetString("txtTerminal_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오는 중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string txtTerminal_ko {
            get {
                return ResourceManager.GetString("txtTerminal_ko", resourceCulture);
            }
        }
    }
}
